#NAME: LEE KEI KAR
#STUDENT ID: 23100598

# Generated by Django 5.2.3 on 2025-06-23 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='task',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteerskill'),
        ),
    ]
