#NAME: LEE KEI KAR
#STUDENT ID: 23100598


# Generated by Django 5.2.3 on 2025-06-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_volunteerassignment_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerassignment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteerskill'),
        ),
    ]
